# version: "3"
# services:
#   react-app:
#     build:
#       context: ./frontend-tsx-side
#       dockerfile: Dockerfile.prod
#       args:
#         - REACT_APP_NAME=vidodo-prod
#     ports:
#       - "8080:80"
