version: "3"
services:
  react-app:
    build: frontend-tsx-side
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-tsx-side/src:/app/src:ro
    environment:
      - REACT_APP_NAME=vidodo
      - WATCHPACK_POLLING=true
#   nginx:
#     image: nginx:stable-alpine
#     ports:
#       - "3001:80"
#     volumes:
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#     depends_on:
#       - backend-app
#   backend-app:
#     container_name: backend-app
#     environment:
#       - PORT=3001
#     depends_on:
#       - mongo

#   mongo:
#     image: mongo
#     # environment:
#     #   - MONGOSH_INITDB_ROOT_USERNAME=idodb
#     #   - MONGOSH_INITDB_ROOT_PASSWORD=mypassword
#     volumes:
#       - mongo-db:/data/db
#   redis:
#     image: redis
# volumes:
#   mongo-db:
