FROM node:19 as build
WORKDIR /app
COPY package.json .
RUN npm install 
COPY . . 
ARG REACT_APP_NAME
ENV REACT_APP_NAME=$REACT_APP_NAME
RUN ["npm","run","build"] 

FROM nginx:1.15.8-alpine
COPY --from=build /app/build /usr/share/nginx/html
