FROM node:19 as builder
WORKDIR /app
COPY package.json .
RUN npm install 
COPY . . 
ARG REACT_APP_NAME
ENV REACT_APP_NAME=$REACT_APP_NAME
RUN ["npm","run","build"] 

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html